import { cpSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig } from "vite";

// ESM context — __dirname unavailable. Use import.meta.url instead.
// import.meta.dirname available from Node 21.2+; fileURLToPath is universal.
const __dirname = dirname(fileURLToPath(import.meta.url));

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Resolve path relative to project root (where this config lives). */
const r = (...segments: string[]) => resolve(__dirname, ...segments);

// ─── MPA page entries ─────────────────────────────────────────────────────────

/**
 * Locale entries — generated by `npm run prebuild`.
 * existsSync guard: first `vite dev` before prebuild won't crash.
 * en → pages/index.html (key "main"), ru/fi → pages/<loc>/index.html.
 */
const localeEntries = Object.fromEntries(
	(
		[
			["main", r("pages/index.html")],
			["ru", r("pages/ru/index.html")],
			["fi", r("pages/fi/index.html")],
		] as Array<[string, string]>
	).filter(([, path]) => existsSync(path)),
);

// 404 entry — built by prebuild
const notFoundEntries = existsSync(r("pages/404.html")) ? { "404": r("pages/404.html") } : {};

const staticEntries = {
	...localeEntries,
	...notFoundEntries,
};

// Auto-discover pattern — use if pages share a common subdirectory structure.
// Example: pages/product/<slug>/index.html
//
// const productEntries = Object.fromEntries(
// 	readdirSync(r("pages/product"), { withFileTypes: true })
// 		.filter((entry) => entry.isDirectory() && existsSync(r("pages/product", entry.name, "index.html")))
// 		.map((entry) => [entry.name, r("pages/product", entry.name, "index.html")]),
// );

// ─── Config ───────────────────────────────────────────────────────────────────

export default defineConfig({
	// Switch to "/" once custom domain timamih.com is active (DNS + Pages settings).
	base: "/timamih_redisign/",

	// HTML root: Vite serves and resolves assets relative to this directory.
	root: r("pages"),

	// Static assets copied as-is to dist/ (favicons, robots.txt, etc.).
	publicDir: r("public"),

	plugins: [
		{
			// Some image references may live in data-* attributes or runtime state,
			// so Vite can't detect them statically. Copy the image tree post-build.
			//
			// Remove this plugin if all image references are static imports
			// or if images are served from a CDN.
			name: "copy-product-images",
			closeBundle() {
				cpSync(r("pages/assets/images"), r("dist/assets/images"), { recursive: true });
			},
		},
	],

	build: {
		outDir: r("dist"),

		// Remove dist/ before each build — prevents stale files accumulating.
		emptyOutDir: true,

		// modulePreload: false — disable <link rel="modulepreload"> injection.
		//
		// MPA rationale: each page is a separate entry with its own small JS chunk.
		// Preloading cross-page chunks wastes bandwidth — users navigate to one page at a time.
		// Re-enable (remove this line) if the project shifts to a shared chunk strategy
		// or adds heavy dynamic imports within a single page.
		modulePreload: false,

		rollupOptions: {
			input: {
				...staticEntries,
				// ...productEntries, // uncomment if using auto-discovery
			},
		},
	},

	resolve: {
		alias: {
			// Must match tsconfig.json "paths" exactly.
			"@assets": r("pages/assets"),
			"@shared": r("pages/shared"),
		},
	},
});
